name:                casebuilder
version:             0.1.0.0
github:              "ruly-rudel/casebuilder"
license:             MIT
author:              "Ruly Rudel"
maintainer:          "ruly.rudel@gmail.com"
copyright:           "2023 Ruly Rudel"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            large case builder
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ruly-rudel/casebuilder#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text
- exceptions
- transformers
- mtl
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  casebuilder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - casebuilder

tests:
  casebuilder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - casebuilder
    - HUnit
